require 'net/https'
require 'ordinalize'
require 'ostruct'
require 'roar/json'

require 'stattleship/version'
require 'stattleship/configuration'
require 'stattleship/client'
require 'stattleship/player'
require 'stattleship/team'
require 'stattleship/stat_leaders'
